# Generated by Django 4.1.3 on 2022-12-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingitem",
            name="shopping_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_list",
                to="shopping.shoppinglist",
            ),
        ),
    ]
