# Generated by Django 4.1.4 on 2022-12-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_shoppingitem_shopping_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingitem",
            name="shopping_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_items",
                to="shopping.shoppinglist",
            ),
        ),
    ]
