# Generated by Django 4.1.4 on 2022-12-20 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopping", "0002_shoppingitem_shopping_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingitem",
            name="shopping_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_items",
                to="shopping.shoppinglist",
            ),
        ),
        migrations.CreateModel(
            name="SharedWith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_with",
                through="shopping.SharedWith",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
