# Generated by Django 4.1.4 on 2022-12-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_alter_shoppingitem_shopping_list_sharedwith_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sharedwith",
            constraint=models.UniqueConstraint(
                fields=("shopping_list", "shared_with"),
                name="unq_shopping_list_shared_with",
            ),
        ),
    ]
