# Generated by Django 4.1.4 on 2022-12-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_alter_shoppingitem_shopping_list"),
        ("shopping", "0004_sharedwith_unq_shopping_list_shared_with"),
    ]

    operations = []
