# Generated by Django 4.1.4 on 2022-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0005_merge_20221221_2256"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="sub_channel",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
