name: Test and Merge

on:
  push:
    pull_request_target:
      branches:
        - main
jobs:
  test:
    name: Unit and API Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shopping_app
          # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-dept: 1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install pipenv tox
          pipenv install
      - name: Run unit and api tests
        env:
          DJANGO_SETTINGS_MODULE: 'core.settings.ci'
        run: |
          cd shopping_app;
          python manage.py test -d --failfast --timing --debug-mode
